### ISSUE TITLE
Having cool game ids like "ahoy-matey-42"

### ISSUE THREAD

**Issue by h4cc** [bigardone/phoenix-battleship#5]
Just a funny little idea: How about generating "funny game ids". So instead of "xtiyRaRh" we could use "ahoy-matey-42" or so.

Inspiration came from heroku with their subdomain names: http://kevinmlawson.com/herokuname/

**Comment by bigardone** [comment]
Sounds good to me! I'll work on it asap, thanks!

**Comment by h4cc** [comment]
Some pirate word sources i found:
https://github.com/mikewesthad/pirate-speak/blob/master/lib/pirate-speak.js
https://gist.github.com/devlaers/1308006

You could also leave this to somebody else to implement - like me :)

**Comment by bigardone** [comment]
Wow! thanks for that resource. We can also use it for the in-game messages and notifications.
If you want to implement the pirate game names go ahead and create a PR, I will appreciate it a lot! :)

**Comment by h4cc** [comment]
Implemented it so far, maybe the list of pirate words could have a checkup and some additions.
