### ISSUE TITLE
blank index page

### ISSUE THREAD

**Issue by mlchai** [bigardone/phoenix-battleship#6]
After following the directions in the readme, visiting localhost:4000 just gives a blank page. I see the title and no errors reported on the server, so I'm not entirely sure what could've caused this. Tried on 2 different computers with the same result. Still new to Elixir/Phoenix though, so could be caused by something I did.

Using Elixir 1.2 + with Node 5.0+ and NPM 3.6+. Tried on ubuntu 14 and OSX 10.11 with Chrome on both.

**Comment by bigardone** [comment]
Hi! Can you share any log messages?

**Comment by mlchai** [comment]
Here's the log I get from the server when I start it and visit the front page:

``` bash
Compiled lib/battleship.ex
lib/battleship/game.ex:114: warning: function create_board/1 is private, @doc's are always discar
ded for private functions
lib/battleship/game.ex:119: warning: function ref/1 is private, @doc's are always discarded for p
rivate functions
Compiled lib/battleship/game.ex
Compiled lib/battleship/game/event.ex
Compiled lib/battleship/game/event_handler.ex
Compiled lib/battleship/game/supervisor.ex
web/channels/player_socket.ex:7: warning: unused alias Player
Compiled web/channels/player_socket.ex
Compiled web/models/ship.ex
Compiled web/gettext.ex
Compiled web/channels/game_channel.ex
Compiled web/views/error_helpers.ex
Compiled lib/battleship/game/board.ex
Compiled web/web.ex
Compiled web/channels/lobby_channel.ex
Compiled web/controllers/page_controller.ex
Compiled web/router.ex
Compiled web/views/error_view.ex
Compiled lib/battleship/endpoint.ex
Compiled web/views/page_view.ex
Compiled web/views/layout_view.ex
Generated battleship app
Consolidated Phoenix.HTML.FormData
Consolidated Poison.Decoder
Consolidated Plug.Exception
Consolidated List.Chars
Consolidated Phoenix.Param
Consolidated Phoenix.HTML.Safe
Consolidated String.Chars
Consolidated Enumerable
Consolidated Collectable
Consolidated Poison.Encoder
Consolidated IEx.Info
Consolidated Inspect
[info] Running Battleship.Endpoint with Cowboy using http on port 4001
26 Apr 07:25:40 - info: compiled in 2.1 sec
[info] GET /
[debug] Processing by Battleship.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 20ms
[info] GET /css/app.css
[debug] Processing by Battleship.PageController.index/2
  Parameters: %{"path" => ["css", "app.css"]}
  Pipelines: [:browser]
[info] Sent 200 in 430µs
[info] GET /js/app.js
[debug] Processing by Battleship.PageController.index/2
  Parameters: %{"path" => ["js", "app.js"]}
  Pipelines: [:browser]
[info] Sent 200 in 334µs
[error] backend port not found: :inotifywait
```

I read that the error has to do with live reload and will try to resolve it tomorrow, don't know if it could make the web page not load at all.

**Comment by bigardone** [comment]
It looks like brunch is not building assets... have you run npm install?

**Comment by mlchai** [comment]
Yeah I ran npm install. How can you tell brunch isn't building assets?

**Comment by bigardone** [comment]
Correct me if I'm wrong but I can't see the brunch compile logs... this is what's the output looks like when I start the server:

```
➜  battleship git:(master) mix phoenix.server
[info] Running Battleship.Endpoint with Cowboy using http on port 4000
26 Apr 15:08:19 - info: compiling
26 Apr 15:08:23 - info: compiling.
26 Apr 15:08:26 - info: compiled 255 files into 2 files, copied 2 in 11 sec
```

Are the `app.js` and `app.css` being built in your `private` folder?

**Comment by mlchai** [comment]
I think you're right, I'm not seeing either of those in my private folder.

**Comment by mlchai** [comment]
Are there any configs or other commands I need to run? I created a new phoenix app and that one seems to be building assets, but this app doesn't seem to be doing it.

**Comment by bigardone** [comment]
I'm using stylus for the stylesheets... can you try installing it to see if that works?

```
$ npm install stylus -g
```

**Comment by mlchai** [comment]
That didn't seem to work. I guess as I go along and learn more about Elixir and Phoenix I may gain the knowledge to fix it.

**Comment by mlchai** [comment]
Pulled the latest commits and had no problems. Seems to be fixed, thanks!
